add retry thingy

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -48,16 +48,26 @@ jobs:
         shell: bash
         run: |
           # Get latest Geode version (and dont put the jq with the curl request, for some reason.)
+          retry_amount=10
           GEODE_VERSION=$(curl -s https://api.github.com/repos/geode-sdk/geode/releases/latest)
+          sleep 2
           GEODE_VERSION=$(echo $GEODE_VERSION | jq -r .tag_name)
           GEODE_VERSION=${GEODE_VERSION#v}
+
           if [ $GEODE_VERSION == null ]; then 
-            GEODE_VERSION=$(curl -s https://api.github.com/repos/geode-sdk/geode/releases/latest)
-            GEODE_VERSION=$(echo $GEODE_VERSION | jq -r .tag_name)
-            GEODE_VERSION=${GEODE_VERSION#v}
+            for i in $(seq $retry_amount)
+            do
+              if [ $GEODE_VERSION == null ]; then 
+                GEODE_VERSION=$(curl -s https://api.github.com/repos/geode-sdk/geode/releases/latest)
+                sleep 2
+                GEODE_VERSION=$(echo $GEODE_VERSION | jq -r .tag_name)
+                GEODE_VERSION=${GEODE_VERSION#v}
+              fi
+            done
           fi
           if [ $GEODE_VERSION == null ]; then 
-            exit "couldn't get le version, try again."
+            echo "couldn't get le version, try again."
+            exit 1;
           fi
 
           # Set path of mod.json file
